<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <ProjectReference Include="../../src/Catalog.Api/Catalog.Api.csproj" />
    <ProjectReference Include="../../src/Web/Web.csproj" />
    <ProjectReference Include="../../src/PublicApi/PublicApi.csproj" />
  </ItemGroup>
</Project>
