name: CatalogService

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/CatalogService.api/**'
      - '.github/workflows/catalog.yml'
  workflow_dispatch:

env:
  PROJECT: src/CatalogService.api/CatalogService.api.csproj
  AZURE_WEBAPP_NAME: app-eshop-catalog

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Publish
      run: dotnet publish ${{ env.PROJECT }} --configuration Release --output ./publish
    - uses: actions/upload-artifact@v4
      with:
        name: catalog
        path: ./publish

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: catalog
        path: ./publish
    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_CATALOG_PUBLISH_PROFILE }}
        package: ./publish